### ISSUE TITLE
Convert Singleton to Scoped for StoreContainer

### ISSUE THREAD

**Issue by ajhrtmn** [the-urlist/BlazorSWA#24]
A singleton will be an app/server wide store, so all users will be using the same instance, which could potentially cause conflicts.

**Comment by burkeholland** [comment]
Is this true for WebAssembly? Since it's all running in the browser?

**Comment by burkeholland** [comment]
This implementation of mine was so bad that I ended up ripping the whole thing out in favor of the straight-up httpclient.
